name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # This will trigger the workflow on tag pushes that start with 'v'
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    # The following steps only run when a tag is pushed
    - name: Check if this is a tag push
      id: check-tag
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          echo "IS_TAG=true" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        fi
    
    - name: List files in target directory
      run: |
        echo "Files in target directory:"
        find target -type f -name "*.jar" | sort
        echo "Files that will be included in release:"
        find target -type f -name "MyWorlds*.jar" | sort
    
    - name: Create GitHub Release
      if: env.IS_TAG == 'true'
      uses: softprops/action-gh-release@v1
      with:
        name: MyWorlds Version ${{ env.VERSION }}
        files: |
          target/MyWorlds*.jar
          !target/*-sources.jar
          !target/*-javadoc.jar
          !target/*-unshaded.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
